### ISSUE TITLE
casci_symm.label_symmetry_ broken by PR #1529?

### ISSUE THREAD

**Issue by MatthewRHermes** [pyscf/pyscf#1548]
The following:
```
from pyscf import gto, scf, mcscf, lib
  
mol = gto.M (atom='Li 0 0 0\nH 1.5 0 0', basis='sto-3g', symmetry=True,
             output=__file__+'.log', verbose=lib.logger.INFO)
mf = scf.RHF (mol).run ()
mc0 = mcscf.CASSCF (mf, 5, 2)
mc0.kernel ()

mc1 = mcscf.CASCI (mf, 5, 2)
mc1.kernel (mc0.mo_coeff, ci0=mc0.ci)
```
Causes the following:
```
Traceback (most recent call last):
  File "lih_casscf25_sto3g.py", line 10, in <module>
    mc1.kernel (mc0.mo_coeff, ci0=mc0.ci)
  File "/home/herme068/anaconda3/envs/pyscf/lib/python3.7/site-packages/pyscf/mcscf/casci_symm.py", line 56, in kernel
    mo_coeff = self.mo_coeff = label_symmetry_(self, mo_coeff, ci0)
  File "/home/herme068/anaconda3/envs/pyscf/lib/python3.7/site-packages/pyscf/mcscf/casci_symm.py", line 151, in label_symmetry_
    wfnsym = mc.fcisolver.guess_wfnsym(mc.ncas, mc.nelecas, ci0, verbose=log)
  File "/home/herme068/anaconda3/envs/pyscf/lib/python3.7/site-packages/pyscf/fci/direct_spin1_symm.py", line 542, in guess_wfnsym
    wfnsym = _guess_wfnsym_cyl_sym(fcivec, strsa, strsb, orbsym)
  File "/home/herme068/anaconda3/envs/pyscf/lib/python3.7/site-packages/pyscf/fci/direct_spin1_symm.py", line 440, in _guess_wfnsym_cyl_sym
    degen_mapping = orbsym.degen_mapping
AttributeError: 'numpy.ndarray' object has no attribute 'degen_mapping'
```
which breaks many of the MC-PDFT unit tests in the pyscf-forge project. I think the issue boils down to some stuff in hf_symm "_finalize" that doesn't get done in the MC-SCF classes (so that mc.mo_coeff doesn't have the "degen_mapping" tag).

**Comment by MatthewRHermes** [comment]
Although really, it's `label_symmetry_` itself that should probably be fixed, since it'd be nice if users could just pass an ndarray from anywhere without worrying about "tagging" it properly...
