### ISSUE TITLE
MacOS h5py error 

### ISSUE THREAD

**Issue by wladerer** [pyscf/pyscf#1592]
macOS Monterey
Anaconda install of PySCF
Python 3.7.16

While trying the PBC tutorial for diamond, I encountered the following error

```
Traceback (most recent call last):
  File "diamond.py", line 20, in <module>
    krks_diamond.kernel()
  File "/Users/wladerer/opt/anaconda3/envs/pyscf/lib/python3.7/site-packages/pyscf/soscf/newton_ah.py", line 882, in kernel
    mo_coeff, mo_occ = self.from_dm(dm)
  File "/Users/wladerer/opt/anaconda3/envs/pyscf/lib/python3.7/site-packages/pyscf/soscf/newton_ah.py", line 924, in from_dm
    vhf = mf.get_veff(mol, dm)
  File "/Users/wladerer/opt/anaconda3/envs/pyscf/lib/python3.7/site-packages/pyscf/pbc/dft/krks.py", line 95, in get_veff
    vj = ks.get_j(cell, dm, hermi, kpts, kpts_band)
  File "/Users/wladerer/opt/anaconda3/envs/pyscf/lib/python3.7/site-packages/pyscf/pbc/scf/khf.py", line 543, in get_j
    vj = self.with_df.get_jk(dm_kpts, hermi, kpts, kpts_band, with_k=False)[0]
  File "/Users/wladerer/opt/anaconda3/envs/pyscf/lib/python3.7/site-packages/pyscf/pbc/df/df.py", line 710, in get_jk
    vj = df_jk.get_j_kpts(self, dm, hermi, kpts, kpts_band)
  File "/Users/wladerer/opt/anaconda3/envs/pyscf/lib/python3.7/site-packages/pyscf/pbc/df/df_jk.py", line 77, in get_j_kpts
    mydf.build(kpts_band=kpts_band)
  File "/Users/wladerer/opt/anaconda3/envs/pyscf/lib/python3.7/site-packages/pyscf/pbc/df/df.py", line 562, in build
    self._make_j3c(self.cell, self.auxcell, kptij_lst, cderi)
  File "/Users/wladerer/opt/anaconda3/envs/pyscf/lib/python3.7/site-packages/pyscf/pbc/df/df.py", line 158, in _make_j3c
    fswap = lib.H5TmpFile(swapfile.name)
  File "/Users/wladerer/opt/anaconda3/envs/pyscf/lib/python3.7/site-packages/pyscf/lib/misc.py", line 874, in __init__
    h5py.File.__init__(self, filename, *args, **kwargs)
  File "/Users/wladerer/opt/anaconda3/envs/pyscf/lib/python3.7/site-packages/h5py/_hl/files.py", line 533, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "/Users/wladerer/opt/anaconda3/envs/pyscf/lib/python3.7/site-packages/h5py/_hl/files.py", line 226, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 106, in h5py.h5f.open
OSError: Unable to open file (file signature not found)
Exception ignored in: <function H5TmpFile.__del__ at 0x7fa04d62d710>
Traceback (most recent call last):
  File "/Users/wladerer/opt/anaconda3/envs/pyscf/lib/python3.7/site-packages/pyscf/lib/misc.py", line 879, in __del__
    self.close()
  File "/Users/wladerer/opt/anaconda3/envs/pyscf/lib/python3.7/site-packages/h5py/_hl/files.py", line 546, in close
    if self.id.valid:
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/Users/wladerer/opt/anaconda3/envs/pyscf/lib/python3.7/site-packages/h5py/_hl/base.py", line 309, in id
    return self._id
AttributeError: 'H5TmpFile' object has no attribute '_id'
```

This error results from the following script 

```
  1 from pyscf.pbc import gto as pbcgto
  2 import numpy as np
  3 cell_diamond = pbcgto.M(atom = '''C     0.      0.      0.
  4                                       C     .8917    .8917   .8917
  5                                       C     1.7834  1.7834  0.
  6                                       C     2.6751  2.6751   .8917
  7                                       C     1.7834  0.      1.7834
  8                                       C     2.6751   .8917  2.6751
  9                                       C     0.      1.7834  1.7834
 10                                       C     .8917   2.6751  2.6751''',
 11                             basis = 'gth-szv',
 12                             pseudo = 'gth-pade',
 13                             a = np.eye(3) * 3.5668)
 14
 15 from pyscf.pbc import dft as pbcdft
 16 kpts = cell_diamond.make_kpts([4] * 3)
 17 krks_diamond = pbcdft.KRKS(cell_diamond, kpts).density_fit(auxbasis='weigend')
 18 krks_diamond.xc = 'bp86'
 19 krks_diamond = krks_diamond.newton()
 20 krks_diamond.kernel()
```

**Comment by fishjojo** [comment]
can you try `pip install pyscf==2.1.1`, and see if there is still a problem.

**Comment by wladerer** [comment]
Resolved. I had to `brew install libomp` as well as `pip install pyscf==2.1.1` . Verified it works on python versions 3.9 and 3.10 using a clean virtual environment.
